---
:backends:
  - yaml
  - eyaml
:yaml:
  :datadir: "%{::boxen_home}/repo/hiera"
:eyaml:
  :datadir: "%{::boxen_home}/repo/hiera"
  :pkcs7_private_key: /Users/marano/keys/private_key.pkcs7.pem
  :pkcs7_public_key:  /Users/marano/keys/public_key.pkcs7.pem
:hierarchy:
  - "users/%{github_login}"
  - common
:merge_behavior: deeper
